name: vilmod
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  splashscreen: ^1.2.0
  font_awesome_flutter: ^8.5.0
  firebase_auth: ^0.15.3+1
  cloud_firestore: ^0.13.0+1
  provider:
  flutter_spinkit:
  bloc_pattern:
  rxdart:
  simple_animations: ^1.3.3
  page_transition: ^1.1.4
  flutter_rating_bar: ^3.0.1+1
  http: ^0.12.0+4
  cached_network_image: ^2.0.0
  flushbar: ^1.10.4
  flutter_form_builder: ^3.10.1
  international_phone_input: ^1.0.4
  intl_phone_number_input: ^0.4.5
  curved_navigation_bar: ^0.3.2
  badges: ^1.1.1
  flutter_braintree: ^0.6.0
  flutter_local_notifications: ^0.8.2
  firebase_messaging: ^6.0.16
  flutter_widget_from_html: ^0.3.2+1
  url_launcher: ^5.4.11
  flutter_inappwebview:
  image_picker:
  firebase_storage:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  fonts:
     - family: OpenSans
       fonts:
         - asset: assets/fonts/OpenSans-Regular.ttf
     - family: CustomIcons
       fonts:
         - asset: assets/fonts/CustomIcons.ttf
     - family: CustomIcon
       fonts:
         - asset: assets/fonts/call.ttf
     - family: Amita
       fonts:
         - asset: assets/fonts/Amita-Regular.ttf
     - family: CormorantInfant
       fonts:
         - asset: assets/fonts/CormorantInfant-Regular.ttf
     - family: SpectralSC
       fonts:
         - asset: assets/fonts/SpectralSC-Regular.ttf
     - family: HindGuntur
       fonts:
         - asset: assets/fonts/HindGuntur-Regular.ttf

